### PR TITLE
Fix AwsShellScript on windows (fix #231)

### LINKED ISSUE #231: AWSShellScript does not work on windows build agent with bash

### PR DESCRIPTION
**Pull request by hunterwerlla**
## Types of changes

-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Added tests
-   [ ] Code cleanup

## Description

This fixes two issues to fix the task
- an errant ' character
- the variable cwd being set somehow before the task runs
## Checklist

-   [ ] I have read the **README** document
-   [ ] I have read the **CONTRIBUTING** document
-   [ ] Local run of `npm run fullBuild` succeeds
-   [ ] I have run tslint against my changes using the root tslint.yaml
-   [ ] My code follows the code style of this project
-   [ ] I have added tests to cover my changes
-   [ ] All new and existing tests passed
-   [ ] A short description of the change has been added to the **CHANGELOG** (CHANGELOG.md) if the change is feature related

## License

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: Tasks/AWSShellScript/TaskOperations.ts [hunk 1]
```diff
@@ -27,20 +27,29 @@ export class TaskOperations {
...
+            } else {
+                workingDirectory = path.dirname(scriptPath)
+            }
+
+            // The solution to this not working on windows comes from doing it like it's done in
+            // the ms task: https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/BashV3/bash.ts
+            // Thanks to the ms team opensourcing their tasks for the solution logic
+            if (process.platform === 'win32') {
+                scriptPath =
+                    (await this.translateWindowsPath(path.dirname(scriptPath))) + `/${path.basename(scriptPath)}`
```
Comment (awschristou) [inline Tasks/AWSShellScript/TaskOperations.ts]: what do you think about using `path.posix.sep` instead of `/` ?

File: Tasks/AWSShellScript/TaskOperations.ts [hunk 2]
```diff
@@ -49,19 +58,49 @@ export class TaskOperations {
...
+                cwd: workingDirectory,
                 env: process.env,
+                errStream: process.stdout,
+                outStream: process.stdout,
                 failOnStdErr: this.taskParameters.failOnStandardError
             }
 
-            // tslint:disable-next-line: no-unsafe-any
-            return await bash.exec(execOptions as tr.IExecOptions)
+            return await bash.exec((execOptions as unknown) as tr.IExecOptions)
```
Comment (awschristou) [inline Tasks/AWSShellScript/TaskOperations.ts]: If we declare `execOptions` as `tr.IExecOptions`, would it eliminate the need for the "as unknown as x" cast?

Comment (hunterwerlla) [reply Tasks/AWSShellScript/TaskOperations.ts]: No, because then it is missing fields from the interface. We could define them as undefined to keep the same behavior, but then strict mode will be mad.

File: Tasks/AWSShellScript/TaskOperations.ts (hunk 1 above)
Comment (hunterwerlla) [reply Tasks/AWSShellScript/TaskOperations.ts]: I think it does not matter either way, changed
